try
{
}
catch (expectedException1 e)
{
}
.
.
.
catch (Exception e)
{
}