try {
  a();
} catch(Exception e) {
  handleMyError(e);
}
b();